# Generated by Django 4.1.7 on 2023-04-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_notification_user_notification_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Comment', 'Comment'), ('Like', 'Like'), ('Chat', 'Chat'), ('Mention', 'Mention')], max_length=25),
        ),
    ]
