# Generated by Django 4.1.7 on 2023-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Comment', 'Comment'), ('Like', 'Like'), ('Chat', 'Chat'), ('Post', 'Post')], max_length=25),
        ),
    ]
