# Generated by Django 4.1.7 on 2023-04-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_invite', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('Follow', 'Follow'), ('Comment', 'Comment'), ('Like', 'Like'), ('Chat', 'Chat'), ('Post', 'Post'), ('Invite', 'Invite')], max_length=25),
        ),
    ]
