# Generated by Django 4.1.7 on 2023-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_notification_invite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='invite',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
