# Generated by Django 4.1.7 on 2023-04-05 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_groupsmoderators_groups_moderators'),
        ('main', '0007_groupinvites_alter_notification_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinvites',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_invites', to='groups.groups'),
        ),
    ]
