# Generated by Django 4.1.7 on 2023-04-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_groupinvites_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default="2023-04-05 12:42:21.290251+02"),
            preserve_default=False,
        ),
    ]
