# Generated by Django 4.1.7 on 2023-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
