# Generated by Django 4.1.7 on 2023-03-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groups_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='groups',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
