# Generated by Django 4.1.7 on 2023-03-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_groups_name_alter_groups_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
