# Generated by Django 4.1.7 on 2023-03-29 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0006_groupposts_groups_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='posts',
            field=models.ManyToManyField(related_name='group_posts', through='groups.GroupPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
