# Generated by Django 4.1.7 on 2023-03-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_groupcomments_groupposts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='picture',
            field=models.ImageField(blank=True, default='../static/images/group-profile.png', null=True, upload_to='images/groups'),
        ),
    ]
