# Generated by Django 4.1.7 on 2023-03-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_alter_groups_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='followers',
        ),
    ]
