# Generated by Django 4.1.7 on 2023-03-31 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0010_remove_groups_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsFollowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='followers',
            field=models.ManyToManyField(related_name='group_user', through='groups.GroupsFollowers', to=settings.AUTH_USER_MODEL),
        ),
    ]
