# Generated by Django 4.1.7 on 2023-03-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_groupsfollowers_groups_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='moderators',
        ),
    ]
